---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: my-nginx-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: test.demo/v1
    resource: my-nginx
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://192.168.5.2:3000/sync
