apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: my-nginx.test.demo
spec:
  group: test.demo
  scope: Namespaced
  names:
    kind: MyNginx
    singular: my-nginx
    plural: my-nginx
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
      subresources:
        status: {}
